name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "34 14 11 5 *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: FantasticFiasco/action-update-license-year@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
